storage:
  class: local-storage
  # class: nfs
  local:
    path: /home/dode/keycloak
  nfs:
    server: 192.168.3.3
    path: /exports/keycloak

keycloak:
  image: quay.io/keycloak/keycloak:20.0.0
  hostname: keycloak.luniks.net
