apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: dode
  labels:
    keycloak.service: database
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    keycloak.service: database
status:
  loadBalancer: {}
