apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: dode
  labels:
    keycloak.service: keycloak
  annotations:
    kubernetes.io/ingress.class: "nginx"    
spec:
  tls:
    - hosts:
      - {{ .Values.keycloak.hostname }}
  rules:
    - host: {{ .Values.keycloak.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
