apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    keycloak.service: keycloak
  name: keycloak
  namespace: dode
spec:
  replicas: 1
  selector:
    matchLabels:
      keycloak.service: keycloak
  strategy: {}
  template:
    metadata:
      labels:
        keycloak.service: keycloak
    spec:
      containers:
      - args:
        - -c
        - standalone.xml
        - -b
        - 0.0.0.0
        - --debug 
        - "*:8585"
        - -Dkeycloak.profile.feature.token_exchange=enabled
        - -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
        env:
        - name: KEYCLOAK_USER
          value: {{ .Values.keycloak.user }}
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-user-secret
              key: password
        - name: DB_VENDOR
          value: {{ .Values.keycloak.database.vendor }}
        - name: DB_ADDR
          value: {{ .Values.keycloak.database.addr }}
        - name: DB_DATABASE
          value: {{ .Values.keycloak.database.database }}
        - name: DB_USER
          value: {{ .Values.keycloak.database.user }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-db-secret
              key: password
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        image: jboss/keycloak
        imagePullPolicy: ""
        name: keycloak
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
