apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: dode
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: local-path
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

